version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5950:5950"
    volumes: 
      - /app/node_modules
      - .:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: process.env.MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: process.env.MONGO_PASSWORD